Default: &defaults
  database: LocalTest.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: LocalTest_test.sqlite3
  <<: *defaults

Staging:
  database: LocalTest_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: LocalTest_production.sqlite3
  poolsize: 100
  <<: *defaults
